backend:
  name: github
  repo: kresimik/auraadriatica-site
  branch: develop
  base_url: https://auraadriatica.com   # samo domena!
  auth_endpoint: /api/auth              # putanja radnika

publish_mode: editorial_workflow
site_url: https://auraadriatica.com
logo_url: /assets/img/logo.png
media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - name: "site_texts"
    label: "Site Texts"
    format: "json"
    editor: { preview: false }
    files:
      - label: "English"
        name: "en"
        file: "content/en.json"
        fields:
          - { label: "Brand", name: "brand", widget: "string" }
          - { label: "Tagline", name: "tagline", widget: "text" }
          # ... (ostala polja kao prije)
